# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
resources:
 repositories:
  - repository: repoDeploy
    type: git
    name: namernews/deploy

trigger:
  branches: 
    include:
    - '*'
  batch: true

pool:
  vmImage: ubuntu-16.04

stages:
- stage: build
  displayName: Build
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: docker.yml@repoDeploy
        parameters:
          imagename: 'hs-id-provider'
